[build]
builder = "NIXPACKS"
buildCommand = "chmod +x build.sh && ./build.sh"

[deploy]
startCommand = "ls -la && ls -la dist && cat dist/server.js || echo 'server.js not found' && node -r dotenv/config dist/server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[services]]
name = "web"
port = 8080
internal_port = 8080
protocol = "http"
health_check_path = "/api/health"

[variables]
NODE_ENV = "production"
PORT = "8080"
CORS_ORIGIN = "https://bill-gen-saas.pages.dev"
DB_PATH = "./data/bills.db"
MONGODB_DB_NAME = "bill-gen"
TEMPLATES_DIR = "./templates" 