[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build:prod"

[deploy]
startCommand = "ls -la && ls -la dist && cat dist/server.js || echo 'server.js not found' && node -r dotenv/config dist/server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[services]]
name = "web"
port = 8080
internal_port = 8080
protocol = "http"
health_check_path = "/api/health"

[variables]
NODE_ENV = "production"
PORT = "8080"
CORS_ORIGINS = "https://bill-gen-production.up.railway.app,https://gunawardanamotors.pages.dev"
DB_PATH = "./data/bills.db"
MONGODB_DB_NAME = "bill-gen"
TEMPLATES_DIR = "./templates"